##############################################################################
# Global configuration--parameters used in multiple scripts
##############################################################################
# Set your email to get notifications for slurm jobs
email: "beckandy@umich.edu"

# inputdir defines the directory containing the prepared VCF and .summary files
inputdir: "/net/bipolar/jedidiah/testpipe"

# parentdir defines the parent directory containing this repository,
# output directories, reference data, etc.
parentdir: "/net/snowwhite/home/beckandy/research/rerun_jed"

# mac defines the minor allele count of variants to examine, provided the
# appropriately named directory exists containing the summarized VCF tables
# valid assignments depend on which summary files have been created by
# vcf_to_summary.pl script:
# -singletons
# -common (all variants with MAC>10)
mac: "singletons"

# adj defines number of bases upstream/downstream per motif
adj: 4

# data defines which set of ERVs to use, either
# "full" (all calls across entire genome)
# "mask" ()
data: "full"

# bin_scheme variable defines how motifs are counted.
# Must be set to one of 3 options:
# "all" (count across entire chromosome)
# "fixed" (fixed-width windows of size binw)
# "band" (use geimsa-staned banding)
bin_scheme: "all"

# binw defines the width of fixed bins in base pairs
binw: 1000000

# Define path to custom user library--used in log_mod.r
# when distributing across jobs nodes that might not have
# all of the same packages installed in shared libraries
libpath: "/net/snowwhite/home/beckandy/R/x86_64-pc-linux-gnu-library/3.3"

# Random seed
rseed: 36087318

##############################################################################
# Define location and naming convention of raw input vcfs, if we are using the
# 'makecopy' option in vcf_to_summary.pl
# rawvcfext defines the suffix of the raw vcfs we want to copy into inputdir
##############################################################################
rawvcfdir: "/net/bipolar/lockeae/final_freeze/snps/vcfs"
rawvcfext: "filtered.sites.modified.vcf.gz"

##############################################################################
# set flags for which files to output when running augment_summary.pl script
##############################################################################
count_motifs: TRUE
expand_summ: TRUE

##############################################################################
# Flags for mod_shell.r
# build_logit sets up data for the motifs+features model;
# you should only need to run this once
#
# negbin_model runs another arm of analysis currently
# under development--no need to set to TRUE at this time
##############################################################################
drop_mispolarized: FALSE
build_logit: FALSE
negbin_model: FALSE

##############################################################################
# ped files containing sample info
##############################################################################
pedfile: "/net/wonderland/home/mattz/BRIDGES/FinalAnalysis/ped/BRIDGES_Assoc.20160226.ped"
plates: "/net/wonderland/home/mattz/BRIDGES/sampleIDs_plates.txt"
# qcped: "/net/bipolar/lockeae/final_freeze/snps/QC/final_freeze.merged.vcfast_vcfdiff_qplot.v2.txt"
qplotfile: "/net/bipolar/bridges/phenotype/qplotstats.txt"
vcfastfile: "/net/bipolar/lockeae/final_freeze/snps/QC/vcfast/final.snps.vcfast.merged.txt"
contamfile: "/net/bipolar/bridges/QC/contamination/clean/contest.txt"
phenofile: "/net/wonderland/home/mattz/BRIDGES/pheno.txt"
pcfile: "/net/wonderland/home/mattz/BRIDGES/Assoc/StudyPCs/BRIDGES_sample_PCA.eigen.evec"

##############################################################################
# Info for processing glf files
##############################################################################
# List of samples, one per line
samples: "/net/bipolar/lockeae/final_freeze/list.txt"

# Directory containing raw glf files
glfdir: "/net/bipolar/bridges/sequencedata/umake/glfs/samples"

##############################################################################
# vcftools fill-aa perl script is needed to add ancestral allele to summaries
##############################################################################
vcftoolsdir: "/net/bipolar/jedidiah/vcftools"
